require('dotenv').config()
const express=require('express')
const mongoose=require("mongoose")
const Redis=require('ioredis')
const cors=require('cors')
const helmet=require('helmet')
const postRoutes=require('./routes/post-routes')
const errorHandler=require('./middleware/errorHandler')
const logger=require('./utils/logger')

const app=express()